### PR TITLE
Add Edhouse job offer to companies.yaml

### PR DESCRIPTION
**Pull request by marekpsenka**

### CODE REVIEW

**Comment by Kobzol** [comment]
Thanks! That's great news that there is a Rust job opening in Moravia :)

I should probably re-design the website soon, since there are many entries already and the bootstrap cards are not very visible/usable.

**Review by Kobzol — APPROVED** [review]

**Comment by Kobzol** [comment]
By the way, you can also post job offers to the #jobhunt channel at the Rust CZ/SK Discord: https://discord.com/channels/984549594572664854/1044960710972670033.

**Comment by marekpsenka** [comment]
> I should probably re-design the website soon, since there are many entries already and the bootstrap cards are not very visible/usable.

@Kobzol Maybe I could try and take a look at that, at least in the companies section. The Zola framework you are using looks very interesting and I would like to learn how it works. I might send you another PR later, depends if I find time.

**Comment by Kobzol** [comment]
Great, if you find the time and can think of a better design, feel free to send a PR :)

**Pull request merged**
